name: emailbot

on:
  workflow_dispatch: #在actions界面点击即可运行
  push:
  schedule:
    #- cron: "33 7 * * *" # 该时间为UTC时间，比北京时间早8个小时，每天早上7点自动执行（需要注意该时间不准时，会有不同程度的分钟数的延迟）
    - cron: "0 23,4 * * *"
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: 
#          python -m pip install --upgrade pip
            pip install -r r.txt
    - run: python ./main.py  #此处为python代码的文件名
    #发送邮件，可选
    - name: 'Send mail' 
      uses: dawidd6/action-send-mail@master
      with:
          # 这些是发送邮件需要配置的参数，更多详细的说明请访问具体的仓库
        server_address: smtp.163.com
        server_port: 465
          # 这些sectret的环境变量需要配置在setting中的secret下
        username: ${{ secrets.EMAILNAME }}  #变量名需与配置的一致
        password: ${{ secrets.EMAILPOP }}
        subject: 每日信息提醒
        body: file://mydata.html
        to: 771457766@qq.com   #填写要收件邮箱名
        from: GitHub Actions
        content_type: text/html

